# Generated by Django 3.1.12 on 2021-10-11 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('age', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('needs', models.CharField(max_length=370)),
            ],
        ),
    ]
